export const UPLOAD_MAP = 'UPLOAD_MAP';
export const UPLOAD_MAP_SUCCESS = 'UPLOAD_MAP_SUCCESS';
export const UPLOAD_MAP_FAILED = 'UPLOAD_MAP_FAILED';

export const ADD_ANCHOR = 'ADD_ANCHOR';
export const ADD_ANCHOR_SUCCESS = 'ADD_ANCHOR_SUCCESS';
export const ADD_ANCHOR_FAILED = 'ADD_ANCHOR_FAILED';

export const UPDATE_ANCHOR = 'UPDATE_ANCHOR';
export const UPDATE_ANCHOR_SUCCESS = 'UPDATE_ANCHOR_SUCCESS';
export const UPDATE_ANCHOR_FAILED = 'UPDATE_ANCHOR_FAILED';

export const DELETE_ANCHOR = 'DELETE_ANCHOR';
export const DELETE_ANCHOR_SUCCESS = 'DELETE_ANCHOR_SUCCESS';
export const DELETE_ANCHOR_FAILED = 'DELETE_ANCHOR_FAILED';
