export const CLEAR_EDITTING_MAP = 'CLEAR_EDITTING_MAP';
export const SET_EDITTING_MAP = 'SET_EDITTING_MAP';

export const GET_AND_SET_EDITTING_MAP = 'GET_AND_SET_EDITTING_MAP';
export const GET_AND_SET_EDITTING_MAP_SUCCESS = 'GET_AND_SET_EDITTING_MAP_SUCCESS';
export const GET_AND_SET_EDITTING_FAILED = 'GET_AND_SET_EDITTING_FAILED';

