export const GET_MAPS = 'GET_MAPS';
export const GET_MAPS_SUCCESS = 'GET_MAPS_SUCCESS';
export const GET_MAPS_FAILED = 'GET_MAPS_FAILED';

export const CREATE_MAP = 'CREATE_MAP';
export const CREATE_MAP_SUCCESS = 'CREATE_MAP_SUCCESS';
export const CREATE_MAP_FAILED = 'CREATE_MAP_FAILED';

export const EDIT_MAP = 'EDIT_MAP';
export const EDIT_MAP_SUCCESS = 'EDIT_MAP_SUCCESS';
export const EDIT_MAP_FAILED = 'SIGN_UP_FAILED';

export const DELETE_MAP = 'DELETE_MAP';
export const DELETE_MAP_SUCCESS = 'DELETE_MAP_SUCCESS';
export const DELETE_MAP_FAILED = 'DELETE_MAP_FAILED';

export const ADD_ANCHOR = 'ADD_ANCHOR';
export const UPDATE_ANCHOR = 'UPDATE_ANCHOR';
export const DELETE_ANCHOR = 'DELETE_ANCHOR';
export const CLEAR_ANCHORS = 'CLEAR_ANCHORS';
