export const GET_MAPS = 'GET_MAPS';
export const GET_MAPS_SUCCESS = 'GET_MAPS_SUCCESS';
export const GET_MAPS_FAILED = 'GET_MAPS_FAILED';

export const ADD_MAP = 'ADD_MAP';
export const ADD_MAP_SUCCESS = 'ADD_MAP_SUCCESS';
export const ADD_MAP_FAILED = 'ADD_MAP_FAILED';

export const UPDATE_MAP = 'UPDATE_MAP';
export const UPDATE_MAP_SUCCESS = 'UPDATE_MAP_SUCCESS';
export const UPDATE_MAP_FAILED = 'UPDATE_MAP_FAILED';

export const DELETE_MAP = 'DELETE_MAP';
export const DELETE_MAP_SUCCESS = 'DELETE_MAP_SUCCESS';
export const DELETE_MAP_FAILED = 'DELETE_MAP_FAILED';

export const ADD_ANCHOR = 'ADD_ANCHOR';
export const ADD_ANCHOR_SUCCESS = 'ADD_ANCHOR_SUCCESS';
export const ADD_ANCHOR_FAILED = 'ADD_ANCHOR_FAILED';

export const UPDATE_ANCHOR = 'UPDATE_ANCHOR';
export const UPDATE_ANCHOR_SUCCESS = 'UPDATE_ANCHOR_SUCCESS';
export const UPDATE_ANCHOR_FAILED = 'UPDATE_ANCHOR_FAILED';

export const DELETE_ANCHOR = 'DELETE_ANCHOR';
export const DELETE_ANCHOR_SUCCESS = 'DELETE_ANCHOR_SUCCESS';
export const DELETE_ANCHOR_FAILED = 'DELETE_ANCHOR_FAILED';
