export const SET_UPLOADING_MAP = 'SET_UPLOADING_MAP';
export const SET_UPLOADING_MAP_SIZE = 'SET_UPLOADING_MAP_SIZE';
export const SET_UPLOADING_MAP_NAME = 'SET_UPLOADING_MAP_NAME';
export const SET_UPLOADING_MAP_RATIO = 'SET_UPLOADING_MAP_RATIO';
export const SET_UPLOADING_MAP_NAME_SUCCESS = 'SET_UPLOADING_MAP_NAME_SUCCESS';
export const SET_UPLOADING_MAP_RATIO_SUCCESS = 'SET_UPLOADING_MAP_RATIO_SUCCESS';
export const CLEAR_UPLOADING_MAP = 'CLEAR_UPLOADING_MAP';

// Actions on anchors which are in creating state, not saved to database
export const ADD_NEW_ANCHOR = 'ADD_NEW_ANCHOR';
export const UPDATE_NEW_ANCHOR = 'UPDATE_NEW_ANCHOR';
export const UPDATE_NEW_ANCHOR_SUCCESS = 'UPDATE_NEW_ANCHOR_SUCCESS';
export const DELETE_NEW_ANCHOR = 'DELETE_NEW_ANCHOR';
export const CLEAR_NEW_ANCHORS = 'CLEAR_NEW_ANCHORS';
